name: airport
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: airport
      POSTGRES_USER: airport
      POSTGRES_DB: airport
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  nginx_logs:
  db_data: