name: airport
services:
  ticket:
    build:
      context: ../
      dockerfile: ticket/build/Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: airport
      DB_PASSWORD: airport
      DB_USER: airport
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - ticket
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: airport
      POSTGRES_USER: airport
      POSTGRES_DB: airport
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "airport", "-U", "airport" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  nginx_logs:
  db_data: