name: airport
services:
  ticket:
    build:
      context: ../
      dockerfile: ticket/build/Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: airport
      DB_PASSWORD: airport
      DB_USER: airport
    depends_on:
      db:
        condition: service_healthy
  usermanager:
    build:
      context: ../
      dockerfile: usermanager/build/Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: airport
      DB_PASSWORD: airport
      DB_USER: airport
      SECRET_KEY: 0oy5hlgbmkglaffrllr@pppw34@4red%
    depends_on:
      db:
        condition: service_healthy
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./lua:/etc/nginx/lua
      - nginx_logs:/var/log/nginx
    depends_on:
      - ticket
      - usermanager
    build:
      dockerfile: Dockerfile.nginx
    environment:
      SECRET_KEY: 0oy5hlgbmkglaffrllr@pppw34@4red%
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: airport
      POSTGRES_USER: airport
      POSTGRES_DB: airport
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U airport -d airport"
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  nginx_logs:
  db_data: